### ISSUE TITLE
Can not run demos as described in Read.me

### ISSUE THREAD

**Issue by renta75** [vbilopav/iHipsterJS#1]
C:\development\iHipsterJS>node run-demos

This script will try to run `http-server` node server from this location, and open `/demos/` url in your default browser.
You may do that manually using any other http server of your choice.

Continue Y/N
Y

(node:14348) UnhandledPromiseRejectionWarning: Error: Cannot find module 'open'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at askQuestion.then.answer (C:\development\iHipsterJS\run-demos.js:30:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\development\iHipsterJS>node -v
v10.15.3

**Comment by vbilopav** [comment]
dev dep missing  "open": "^6.3.0"

just install https://github.com/vbilopav/iHipsterJS/blob/master/package.json or use another web server
